export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN'
export const CREATE_CAMPAIGN_FAIL = 'CREATE_CAMPAIGN_FAIL'

export const GET_CAMPAIGN = 'GET_CAMPAIGN'
export const GET_CAMPAIGN_FAIL = 'GET_CAMPAIGN_FAIL'

export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN'
export const DELETE_CAMPAIGN_FAIL = 'DELETE_CAMPAIGN_FAIL'

export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN'
export const UPDATE_CAMPAIGN_FAIL = 'UPDATE_CAMPAIGN_FAIL'

export const GET_CAMPAIGN_DETAILS = 'GET_CAMPAIGN_DETAILS'
export const GET_CAMPAIGN_DETAILS_FAIL = 'GET_CAMPAIGN_DETAILS_FAIL'
